# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 0, 1, 2)
        self.run_Button = QtWidgets.QPushButton(self.centralwidget)
        self.run_Button.setObjectName("run_Button")
        self.gridLayout.addWidget(self.run_Button, 6, 1, 1, 1)
        self.command_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.command_lineEdit.setObjectName("command_lineEdit")
        self.gridLayout.addWidget(self.command_lineEdit, 6, 0, 1, 1)
        self.formFrame = QtWidgets.QFrame(self.centralwidget)
        self.formFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.formFrame)
        self.password_label.setObjectName("password_label")
        self.gridLayout_3.addWidget(self.password_label, 2, 0, 1, 1)
        self.connect_Button = QtWidgets.QPushButton(self.formFrame)
        self.connect_Button.setObjectName("connect_Button")
        self.gridLayout_3.addWidget(self.connect_Button, 3, 1, 1, 1)
        self.ipaddress_label = QtWidgets.QLabel(self.formFrame)
        self.ipaddress_label.setObjectName("ipaddress_label")
        self.gridLayout_3.addWidget(self.ipaddress_label, 0, 0, 1, 1)
        self.usernam_label = QtWidgets.QLabel(self.formFrame)
        self.usernam_label.setObjectName("usernam_label")
        self.gridLayout_3.addWidget(self.usernam_label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 2, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.password_lineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout_3.addWidget(self.password_lineEdit, 2, 1, 1, 2)
        self.username_lineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.gridLayout_3.addWidget(self.username_lineEdit, 1, 1, 1, 2)
        self.ipaddress_lineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.ipaddress_lineEdit.setObjectName("ipaddress_lineEdit")
        self.gridLayout_3.addWidget(self.ipaddress_lineEdit, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.formFrame, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ipaddress_lineEdit, self.username_lineEdit)
        MainWindow.setTabOrder(self.username_lineEdit, self.password_lineEdit)
        MainWindow.setTabOrder(self.password_lineEdit, self.connect_Button)
        MainWindow.setTabOrder(self.connect_Button, self.command_lineEdit)
        MainWindow.setTabOrder(self.command_lineEdit, self.run_Button)
        MainWindow.setTabOrder(self.run_Button, self.plainTextEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run_Button.setText(_translate("MainWindow", "run"))
        self.password_label.setText(_translate("MainWindow", "password"))
        self.connect_Button.setText(_translate("MainWindow", "connect"))
        self.ipaddress_label.setText(_translate("MainWindow", "ip address"))
        self.usernam_label.setText(_translate("MainWindow", "username"))
        self.ipaddress_lineEdit.setText(_translate("MainWindow", "127.0.0.1"))
